language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
sudo: false
env: PERL_CPANM_OPT="--notest --force --skip-satisfied"
before_install:
  - "cpanm Dist::Zilla"
  - "dzil authordeps | cpanm"
  - "dzil listdeps --author | cpanm"
  - "dzil build"
install: "dzil listdeps | cpanm"
script: "dzil test --author"
